### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by VovaMobile**
This is a first Ukrainian translation for this addon.

### CODE REVIEW

**Comment by hxebolax** [comment]
Hello, thank you very much for your work.

Comment that I added you to the credits in the readme. I put your Github name if you want another one to appear or you do not want to be please tell me.

Well before I release the version I would like you to test the version I generate with your language. Internally I have to generate automatically every time I add a language the countries of the world so I would like you to tell me if they appear in your language correctly when you are in the area search by countries.

https://www.dropbox.com/s/ikgzvdnkbu32lnp/zRadio-0.5.7.nvda-addon?dl=1

Thank you very much.

**Comment by VovaMobile** [comment]
Hello, I don't mind you adding my name to the list of contributors.
The add-on works fine, but I inadvertently suggested the wrong file.
Can I send you a more literary translation?

2022-05-30 11:14 GMT+03:00, hxebolax ***@***.***>:

**Comment by hxebolax** [comment]
No problem sending it.

So what I was worried about was the name of the countries. If they go well the rest is easy.

As soon as I have your new translation I will add it and in the next few days I will release the update.

Thank you very much.

**Comment by VovaMobile** [comment]
Hi, names of some countries not translated into Ukrainian and names of
some languages translated incorrect. How to fix this?

2022-05-30 12:20 GMT+03:00, hxebolax ***@***.***>:

**Comment by hxebolax** [comment]
Hello, hardly fixable.

The country names are automatically generated by PyCountry, a Python library.

In the plugin directory in the dictionary.py file is the dictionaries including the Ukrainian I decided not to put that to translate for the translators because it seems to me too much for them to translate since there are many countries.

If you want you can take a look at it and send me back if you consider the modified dictionary, as I said it is automatically generated.

As for the languages it is more difficult because they are languages returned by the server and when I made the add-on the library returned only the language which now also returns the code.

The problem is that zRadio was an experiment as the first add-on for NVDA that I made and nowadays I don't like its code at all because of the learning process.

I plan to make it from scratch in the future applying the knowledge acquired in these years together with improvements that I think it needs, but I do not plan to modify the code except to make it compatible with the different versions of NVDA that are coming out until I release the new add-on.


Translated with www.DeepL.com/Translator (free version)

**Pull request merged**
